title: "DANIEL WHISKERPANTS"
logo: "/assets/images/Gemini_Generated_Image_x8njc2x8njc2x8nj.jpeg"
description: "I code like a pro, make machines work for me, drink coffee like it’s water, and occasionally pretend to understand algorithms. Currently conquering tech, one bug at a time."
show_downloads: false
theme: jekyll-theme-minimal
